// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: casbin/casbin.proto

package casbin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewEnforcerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelText     string                 `protobuf:"bytes,1,opt,name=modelText,proto3" json:"modelText,omitempty"`
	AdapterHandle int32                  `protobuf:"varint,2,opt,name=adapterHandle,proto3" json:"adapterHandle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewEnforcerRequest) Reset() {
	*x = NewEnforcerRequest{}
	mi := &file_casbin_casbin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewEnforcerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewEnforcerRequest) ProtoMessage() {}

func (x *NewEnforcerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_casbin_casbin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewEnforcerRequest.ProtoReflect.Descriptor instead.
func (*NewEnforcerRequest) Descriptor() ([]byte, []int) {
	return file_casbin_casbin_proto_rawDescGZIP(), []int{0}
}

func (x *NewEnforcerRequest) GetModelText() string {
	if x != nil {
		return x.ModelText
	}
	return ""
}

func (x *NewEnforcerRequest) GetAdapterHandle() int32 {
	if x != nil {
		return x.AdapterHandle
	}
	return 0
}

type NewEnforcerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handler       int32                  `protobuf:"varint,1,opt,name=handler,proto3" json:"handler,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewEnforcerReply) Reset() {
	*x = NewEnforcerReply{}
	mi := &file_casbin_casbin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewEnforcerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewEnforcerReply) ProtoMessage() {}

func (x *NewEnforcerReply) ProtoReflect() protoreflect.Message {
	mi := &file_casbin_casbin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewEnforcerReply.ProtoReflect.Descriptor instead.
func (*NewEnforcerReply) Descriptor() ([]byte, []int) {
	return file_casbin_casbin_proto_rawDescGZIP(), []int{1}
}

func (x *NewEnforcerReply) GetHandler() int32 {
	if x != nil {
		return x.Handler
	}
	return 0
}

type NewAdapterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdapterName   string                 `protobuf:"bytes,1,opt,name=adapterName,proto3" json:"adapterName,omitempty"`
	DriverName    string                 `protobuf:"bytes,2,opt,name=driverName,proto3" json:"driverName,omitempty"`
	ConnectString string                 `protobuf:"bytes,3,opt,name=connectString,proto3" json:"connectString,omitempty"`
	DbSpecified   bool                   `protobuf:"varint,4,opt,name=dbSpecified,proto3" json:"dbSpecified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewAdapterRequest) Reset() {
	*x = NewAdapterRequest{}
	mi := &file_casbin_casbin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewAdapterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewAdapterRequest) ProtoMessage() {}

func (x *NewAdapterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_casbin_casbin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewAdapterRequest.ProtoReflect.Descriptor instead.
func (*NewAdapterRequest) Descriptor() ([]byte, []int) {
	return file_casbin_casbin_proto_rawDescGZIP(), []int{2}
}

func (x *NewAdapterRequest) GetAdapterName() string {
	if x != nil {
		return x.AdapterName
	}
	return ""
}

func (x *NewAdapterRequest) GetDriverName() string {
	if x != nil {
		return x.DriverName
	}
	return ""
}

func (x *NewAdapterRequest) GetConnectString() string {
	if x != nil {
		return x.ConnectString
	}
	return ""
}

func (x *NewAdapterRequest) GetDbSpecified() bool {
	if x != nil {
		return x.DbSpecified
	}
	return false
}

type NewAdapterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handler       int32                  `protobuf:"varint,1,opt,name=handler,proto3" json:"handler,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewAdapterReply) Reset() {
	*x = NewAdapterReply{}
	mi := &file_casbin_casbin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewAdapterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewAdapterReply) ProtoMessage() {}

func (x *NewAdapterReply) ProtoReflect() protoreflect.Message {
	mi := &file_casbin_casbin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewAdapterReply.ProtoReflect.Descriptor instead.
func (*NewAdapterReply) Descriptor() ([]byte, []int) {
	return file_casbin_casbin_proto_rawDescGZIP(), []int{3}
}

func (x *NewAdapterReply) GetHandler() int32 {
	if x != nil {
		return x.Handler
	}
	return 0
}

type EnforceRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnforcerHandler int32                  `protobuf:"varint,1,opt,name=enforcerHandler,proto3" json:"enforcerHandler,omitempty"`
	Params          []string               `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnforceRequest) Reset() {
	*x = EnforceRequest{}
	mi := &file_casbin_casbin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnforceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnforceRequest) ProtoMessage() {}

func (x *EnforceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_casbin_casbin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnforceRequest.ProtoReflect.Descriptor instead.
func (*EnforceRequest) Descriptor() ([]byte, []int) {
	return file_casbin_casbin_proto_rawDescGZIP(), []int{4}
}

func (x *EnforceRequest) GetEnforcerHandler() int32 {
	if x != nil {
		return x.EnforcerHandler
	}
	return 0
}

func (x *EnforceRequest) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

type BoolReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Res           bool                   `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolReply) Reset() {
	*x = BoolReply{}
	mi := &file_casbin_casbin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolReply) ProtoMessage() {}

func (x *BoolReply) ProtoReflect() protoreflect.Message {
	mi := &file_casbin_casbin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolReply.ProtoReflect.Descriptor instead.
func (*BoolReply) Descriptor() ([]byte, []int) {
	return file_casbin_casbin_proto_rawDescGZIP(), []int{5}
}

func (x *BoolReply) GetRes() bool {
	if x != nil {
		return x.Res
	}
	return false
}

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handler       int32                  `protobuf:"varint,1,opt,name=handler,proto3" json:"handler,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_casbin_casbin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_casbin_casbin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_casbin_casbin_proto_rawDescGZIP(), []int{6}
}

func (x *EmptyRequest) GetHandler() int32 {
	if x != nil {
		return x.Handler
	}
	return 0
}

type EmptyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyReply) Reset() {
	*x = EmptyReply{}
	mi := &file_casbin_casbin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReply) ProtoMessage() {}

func (x *EmptyReply) ProtoReflect() protoreflect.Message {
	mi := &file_casbin_casbin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReply.ProtoReflect.Descriptor instead.
func (*EmptyReply) Descriptor() ([]byte, []int) {
	return file_casbin_casbin_proto_rawDescGZIP(), []int{7}
}

type PolicyRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnforcerHandler int32                  `protobuf:"varint,1,opt,name=enforcerHandler,proto3" json:"enforcerHandler,omitempty"`
	PType           string                 `protobuf:"bytes,2,opt,name=pType,proto3" json:"pType,omitempty"`
	Params          []string               `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PolicyRequest) Reset() {
	*x = PolicyRequest{}
	mi := &file_casbin_casbin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyRequest) ProtoMessage() {}

func (x *PolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_casbin_casbin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyRequest.ProtoReflect.Descriptor instead.
func (*PolicyRequest) Descriptor() ([]byte, []int) {
	return file_casbin_casbin_proto_rawDescGZIP(), []int{8}
}

func (x *PolicyRequest) GetEnforcerHandler() int32 {
	if x != nil {
		return x.EnforcerHandler
	}
	return 0
}

func (x *PolicyRequest) GetPType() string {
	if x != nil {
		return x.PType
	}
	return ""
}

func (x *PolicyRequest) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

type SimpleGetRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnforcerHandler int32                  `protobuf:"varint,1,opt,name=enforcerHandler,proto3" json:"enforcerHandler,omitempty"`
	PType           string                 `protobuf:"bytes,2,opt,name=pType,proto3" json:"pType,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SimpleGetRequest) Reset() {
	*x = SimpleGetRequest{}
	mi := &file_casbin_casbin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleGetRequest) ProtoMessage() {}

func (x *SimpleGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_casbin_casbin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleGetRequest.ProtoReflect.Descriptor instead.
func (*SimpleGetRequest) Descriptor() ([]byte, []int) {
	return file_casbin_casbin_proto_rawDescGZIP(), []int{9}
}

func (x *SimpleGetRequest) GetEnforcerHandler() int32 {
	if x != nil {
		return x.EnforcerHandler
	}
	return 0
}

func (x *SimpleGetRequest) GetPType() string {
	if x != nil {
		return x.PType
	}
	return ""
}

type ArrayReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Array         []string               `protobuf:"bytes,1,rep,name=array,proto3" json:"array,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrayReply) Reset() {
	*x = ArrayReply{}
	mi := &file_casbin_casbin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrayReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayReply) ProtoMessage() {}

func (x *ArrayReply) ProtoReflect() protoreflect.Message {
	mi := &file_casbin_casbin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayReply.ProtoReflect.Descriptor instead.
func (*ArrayReply) Descriptor() ([]byte, []int) {
	return file_casbin_casbin_proto_rawDescGZIP(), []int{10}
}

func (x *ArrayReply) GetArray() []string {
	if x != nil {
		return x.Array
	}
	return nil
}

type FilteredPolicyRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnforcerHandler int32                  `protobuf:"varint,1,opt,name=enforcerHandler,proto3" json:"enforcerHandler,omitempty"`
	PType           string                 `protobuf:"bytes,2,opt,name=pType,proto3" json:"pType,omitempty"`
	FieldIndex      int32                  `protobuf:"varint,3,opt,name=fieldIndex,proto3" json:"fieldIndex,omitempty"`
	FieldValues     []string               `protobuf:"bytes,4,rep,name=fieldValues,proto3" json:"fieldValues,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FilteredPolicyRequest) Reset() {
	*x = FilteredPolicyRequest{}
	mi := &file_casbin_casbin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilteredPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilteredPolicyRequest) ProtoMessage() {}

func (x *FilteredPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_casbin_casbin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilteredPolicyRequest.ProtoReflect.Descriptor instead.
func (*FilteredPolicyRequest) Descriptor() ([]byte, []int) {
	return file_casbin_casbin_proto_rawDescGZIP(), []int{11}
}

func (x *FilteredPolicyRequest) GetEnforcerHandler() int32 {
	if x != nil {
		return x.EnforcerHandler
	}
	return 0
}

func (x *FilteredPolicyRequest) GetPType() string {
	if x != nil {
		return x.PType
	}
	return ""
}

func (x *FilteredPolicyRequest) GetFieldIndex() int32 {
	if x != nil {
		return x.FieldIndex
	}
	return 0
}

func (x *FilteredPolicyRequest) GetFieldValues() []string {
	if x != nil {
		return x.FieldValues
	}
	return nil
}

type UserRoleRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnforcerHandler int32                  `protobuf:"varint,1,opt,name=enforcerHandler,proto3" json:"enforcerHandler,omitempty"`
	User            string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Role            string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserRoleRequest) Reset() {
	*x = UserRoleRequest{}
	mi := &file_casbin_casbin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRoleRequest) ProtoMessage() {}

func (x *UserRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_casbin_casbin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRoleRequest.ProtoReflect.Descriptor instead.
func (*UserRoleRequest) Descriptor() ([]byte, []int) {
	return file_casbin_casbin_proto_rawDescGZIP(), []int{12}
}

func (x *UserRoleRequest) GetEnforcerHandler() int32 {
	if x != nil {
		return x.EnforcerHandler
	}
	return 0
}

func (x *UserRoleRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *UserRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type PermissionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnforcerHandler int32                  `protobuf:"varint,1,opt,name=enforcerHandler,proto3" json:"enforcerHandler,omitempty"`
	User            string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Permissions     []string               `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PermissionRequest) Reset() {
	*x = PermissionRequest{}
	mi := &file_casbin_casbin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionRequest) ProtoMessage() {}

func (x *PermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_casbin_casbin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionRequest.ProtoReflect.Descriptor instead.
func (*PermissionRequest) Descriptor() ([]byte, []int) {
	return file_casbin_casbin_proto_rawDescGZIP(), []int{13}
}

func (x *PermissionRequest) GetEnforcerHandler() int32 {
	if x != nil {
		return x.EnforcerHandler
	}
	return 0
}

func (x *PermissionRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *PermissionRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type Array2DReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	D2            []*Array2DReplyD       `protobuf:"bytes,1,rep,name=d2,proto3" json:"d2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Array2DReply) Reset() {
	*x = Array2DReply{}
	mi := &file_casbin_casbin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Array2DReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Array2DReply) ProtoMessage() {}

func (x *Array2DReply) ProtoReflect() protoreflect.Message {
	mi := &file_casbin_casbin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Array2DReply.ProtoReflect.Descriptor instead.
func (*Array2DReply) Descriptor() ([]byte, []int) {
	return file_casbin_casbin_proto_rawDescGZIP(), []int{14}
}

func (x *Array2DReply) GetD2() []*Array2DReplyD {
	if x != nil {
		return x.D2
	}
	return nil
}

type Array struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Array         []string               `protobuf:"bytes,1,rep,name=array,proto3" json:"array,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Array) Reset() {
	*x = Array{}
	mi := &file_casbin_casbin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Array) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Array) ProtoMessage() {}

func (x *Array) ProtoReflect() protoreflect.Message {
	mi := &file_casbin_casbin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Array.ProtoReflect.Descriptor instead.
func (*Array) Descriptor() ([]byte, []int) {
	return file_casbin_casbin_proto_rawDescGZIP(), []int{15}
}

func (x *Array) GetArray() []string {
	if x != nil {
		return x.Array
	}
	return nil
}

type Array2D struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Array         []*Array               `protobuf:"bytes,1,rep,name=array,proto3" json:"array,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Array2D) Reset() {
	*x = Array2D{}
	mi := &file_casbin_casbin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Array2D) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Array2D) ProtoMessage() {}

func (x *Array2D) ProtoReflect() protoreflect.Message {
	mi := &file_casbin_casbin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Array2D.ProtoReflect.Descriptor instead.
func (*Array2D) Descriptor() ([]byte, []int) {
	return file_casbin_casbin_proto_rawDescGZIP(), []int{16}
}

func (x *Array2D) GetArray() []*Array {
	if x != nil {
		return x.Array
	}
	return nil
}

type UpdatePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Old           *Array                 `protobuf:"bytes,1,opt,name=old,proto3" json:"old,omitempty"`
	New           *Array                 `protobuf:"bytes,2,opt,name=new,proto3" json:"new,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePolicyRequest) Reset() {
	*x = UpdatePolicyRequest{}
	mi := &file_casbin_casbin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePolicyRequest) ProtoMessage() {}

func (x *UpdatePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_casbin_casbin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePolicyRequest.ProtoReflect.Descriptor instead.
func (*UpdatePolicyRequest) Descriptor() ([]byte, []int) {
	return file_casbin_casbin_proto_rawDescGZIP(), []int{17}
}

func (x *UpdatePolicyRequest) GetOld() *Array {
	if x != nil {
		return x.Old
	}
	return nil
}

func (x *UpdatePolicyRequest) GetNew() *Array {
	if x != nil {
		return x.New
	}
	return nil
}

type UpdatePoliciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Old           *Array2D               `protobuf:"bytes,1,opt,name=old,proto3" json:"old,omitempty"`
	New           *Array2D               `protobuf:"bytes,2,opt,name=new,proto3" json:"new,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePoliciesRequest) Reset() {
	*x = UpdatePoliciesRequest{}
	mi := &file_casbin_casbin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePoliciesRequest) ProtoMessage() {}

func (x *UpdatePoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_casbin_casbin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePoliciesRequest.ProtoReflect.Descriptor instead.
func (*UpdatePoliciesRequest) Descriptor() ([]byte, []int) {
	return file_casbin_casbin_proto_rawDescGZIP(), []int{18}
}

func (x *UpdatePoliciesRequest) GetOld() *Array2D {
	if x != nil {
		return x.Old
	}
	return nil
}

func (x *UpdatePoliciesRequest) GetNew() *Array2D {
	if x != nil {
		return x.New
	}
	return nil
}

type Array2DReplyD struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	D1            []string               `protobuf:"bytes,1,rep,name=d1,proto3" json:"d1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Array2DReplyD) Reset() {
	*x = Array2DReplyD{}
	mi := &file_casbin_casbin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Array2DReplyD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Array2DReplyD) ProtoMessage() {}

func (x *Array2DReplyD) ProtoReflect() protoreflect.Message {
	mi := &file_casbin_casbin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Array2DReplyD.ProtoReflect.Descriptor instead.
func (*Array2DReplyD) Descriptor() ([]byte, []int) {
	return file_casbin_casbin_proto_rawDescGZIP(), []int{14, 0}
}

func (x *Array2DReplyD) GetD1() []string {
	if x != nil {
		return x.D1
	}
	return nil
}

var File_casbin_casbin_proto protoreflect.FileDescriptor

const file_casbin_casbin_proto_rawDesc = "" +
	"\n" +
	"\x13casbin/casbin.proto\x12\x06casbin\"X\n" +
	"\x12NewEnforcerRequest\x12\x1c\n" +
	"\tmodelText\x18\x01 \x01(\tR\tmodelText\x12$\n" +
	"\radapterHandle\x18\x02 \x01(\x05R\radapterHandle\",\n" +
	"\x10NewEnforcerReply\x12\x18\n" +
	"\ahandler\x18\x01 \x01(\x05R\ahandler\"\x9d\x01\n" +
	"\x11NewAdapterRequest\x12 \n" +
	"\vadapterName\x18\x01 \x01(\tR\vadapterName\x12\x1e\n" +
	"\n" +
	"driverName\x18\x02 \x01(\tR\n" +
	"driverName\x12$\n" +
	"\rconnectString\x18\x03 \x01(\tR\rconnectString\x12 \n" +
	"\vdbSpecified\x18\x04 \x01(\bR\vdbSpecified\"+\n" +
	"\x0fNewAdapterReply\x12\x18\n" +
	"\ahandler\x18\x01 \x01(\x05R\ahandler\"R\n" +
	"\x0eEnforceRequest\x12(\n" +
	"\x0fenforcerHandler\x18\x01 \x01(\x05R\x0fenforcerHandler\x12\x16\n" +
	"\x06params\x18\x02 \x03(\tR\x06params\"\x1d\n" +
	"\tBoolReply\x12\x10\n" +
	"\x03res\x18\x01 \x01(\bR\x03res\"(\n" +
	"\fEmptyRequest\x12\x18\n" +
	"\ahandler\x18\x01 \x01(\x05R\ahandler\"\f\n" +
	"\n" +
	"EmptyReply\"g\n" +
	"\rPolicyRequest\x12(\n" +
	"\x0fenforcerHandler\x18\x01 \x01(\x05R\x0fenforcerHandler\x12\x14\n" +
	"\x05pType\x18\x02 \x01(\tR\x05pType\x12\x16\n" +
	"\x06params\x18\x03 \x03(\tR\x06params\"R\n" +
	"\x10SimpleGetRequest\x12(\n" +
	"\x0fenforcerHandler\x18\x01 \x01(\x05R\x0fenforcerHandler\x12\x14\n" +
	"\x05pType\x18\x02 \x01(\tR\x05pType\"\"\n" +
	"\n" +
	"ArrayReply\x12\x14\n" +
	"\x05array\x18\x01 \x03(\tR\x05array\"\x99\x01\n" +
	"\x15FilteredPolicyRequest\x12(\n" +
	"\x0fenforcerHandler\x18\x01 \x01(\x05R\x0fenforcerHandler\x12\x14\n" +
	"\x05pType\x18\x02 \x01(\tR\x05pType\x12\x1e\n" +
	"\n" +
	"fieldIndex\x18\x03 \x01(\x05R\n" +
	"fieldIndex\x12 \n" +
	"\vfieldValues\x18\x04 \x03(\tR\vfieldValues\"c\n" +
	"\x0fUserRoleRequest\x12(\n" +
	"\x0fenforcerHandler\x18\x01 \x01(\x05R\x0fenforcerHandler\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"s\n" +
	"\x11PermissionRequest\x12(\n" +
	"\x0fenforcerHandler\x18\x01 \x01(\x05R\x0fenforcerHandler\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12 \n" +
	"\vpermissions\x18\x03 \x03(\tR\vpermissions\"K\n" +
	"\fArray2DReply\x12&\n" +
	"\x02d2\x18\x01 \x03(\v2\x16.casbin.Array2DReply.dR\x02d2\x1a\x13\n" +
	"\x01d\x12\x0e\n" +
	"\x02d1\x18\x01 \x03(\tR\x02d1\"\x1d\n" +
	"\x05Array\x12\x14\n" +
	"\x05array\x18\x01 \x03(\tR\x05array\".\n" +
	"\aArray2D\x12#\n" +
	"\x05array\x18\x01 \x03(\v2\r.casbin.ArrayR\x05array\"W\n" +
	"\x13UpdatePolicyRequest\x12\x1f\n" +
	"\x03old\x18\x01 \x01(\v2\r.casbin.ArrayR\x03old\x12\x1f\n" +
	"\x03new\x18\x02 \x01(\v2\r.casbin.ArrayR\x03new\"]\n" +
	"\x15UpdatePoliciesRequest\x12!\n" +
	"\x03old\x18\x01 \x01(\v2\x0f.casbin.Array2DR\x03old\x12!\n" +
	"\x03new\x18\x02 \x01(\v2\x0f.casbin.Array2DR\x03new2\xf3\x14\n" +
	"\x06Casbin\x12E\n" +
	"\vNewEnforcer\x12\x1a.casbin.NewEnforcerRequest\x1a\x18.casbin.NewEnforcerReply\"\x00\x12B\n" +
	"\n" +
	"NewAdapter\x12\x19.casbin.NewAdapterRequest\x1a\x17.casbin.NewAdapterReply\"\x00\x126\n" +
	"\aEnforce\x12\x16.casbin.EnforceRequest\x1a\x11.casbin.BoolReply\"\x00\x128\n" +
	"\n" +
	"LoadPolicy\x12\x14.casbin.EmptyRequest\x1a\x12.casbin.EmptyReply\"\x00\x128\n" +
	"\n" +
	"SavePolicy\x12\x14.casbin.EmptyRequest\x1a\x12.casbin.EmptyReply\"\x00\x127\n" +
	"\tAddPolicy\x12\x15.casbin.PolicyRequest\x1a\x11.casbin.BoolReply\"\x00\x12<\n" +
	"\x0eAddNamedPolicy\x12\x15.casbin.PolicyRequest\x1a\x11.casbin.BoolReply\"\x00\x12:\n" +
	"\fRemovePolicy\x12\x15.casbin.PolicyRequest\x1a\x11.casbin.BoolReply\"\x00\x12?\n" +
	"\x11RemoveNamedPolicy\x12\x15.casbin.PolicyRequest\x1a\x11.casbin.BoolReply\"\x00\x12J\n" +
	"\x14RemoveFilteredPolicy\x12\x1d.casbin.FilteredPolicyRequest\x1a\x11.casbin.BoolReply\"\x00\x12O\n" +
	"\x19RemoveFilteredNamedPolicy\x12\x1d.casbin.FilteredPolicyRequest\x1a\x11.casbin.BoolReply\"\x00\x129\n" +
	"\tGetPolicy\x12\x14.casbin.EmptyRequest\x1a\x14.casbin.Array2DReply\"\x00\x12?\n" +
	"\x0eGetNamedPolicy\x12\x15.casbin.PolicyRequest\x1a\x14.casbin.Array2DReply\"\x00\x12J\n" +
	"\x11GetFilteredPolicy\x12\x1d.casbin.FilteredPolicyRequest\x1a\x14.casbin.Array2DReply\"\x00\x12O\n" +
	"\x16GetFilteredNamedPolicy\x12\x1d.casbin.FilteredPolicyRequest\x1a\x14.casbin.Array2DReply\"\x00\x12?\n" +
	"\x11AddGroupingPolicy\x12\x15.casbin.PolicyRequest\x1a\x11.casbin.BoolReply\"\x00\x12D\n" +
	"\x16AddNamedGroupingPolicy\x12\x15.casbin.PolicyRequest\x1a\x11.casbin.BoolReply\"\x00\x12B\n" +
	"\x14RemoveGroupingPolicy\x12\x15.casbin.PolicyRequest\x1a\x11.casbin.BoolReply\"\x00\x12G\n" +
	"\x19RemoveNamedGroupingPolicy\x12\x15.casbin.PolicyRequest\x1a\x11.casbin.BoolReply\"\x00\x12R\n" +
	"\x1cRemoveFilteredGroupingPolicy\x12\x1d.casbin.FilteredPolicyRequest\x1a\x11.casbin.BoolReply\"\x00\x12W\n" +
	"!RemoveFilteredNamedGroupingPolicy\x12\x1d.casbin.FilteredPolicyRequest\x1a\x11.casbin.BoolReply\"\x00\x12A\n" +
	"\x11GetGroupingPolicy\x12\x14.casbin.EmptyRequest\x1a\x14.casbin.Array2DReply\"\x00\x12G\n" +
	"\x16GetNamedGroupingPolicy\x12\x15.casbin.PolicyRequest\x1a\x14.casbin.Array2DReply\"\x00\x12R\n" +
	"\x19GetFilteredGroupingPolicy\x12\x1d.casbin.FilteredPolicyRequest\x1a\x14.casbin.Array2DReply\"\x00\x12W\n" +
	"\x1eGetFilteredNamedGroupingPolicy\x12\x1d.casbin.FilteredPolicyRequest\x1a\x14.casbin.Array2DReply\"\x00\x12<\n" +
	"\x0eGetAllSubjects\x12\x14.casbin.EmptyRequest\x1a\x12.casbin.ArrayReply\"\x00\x12E\n" +
	"\x13GetAllNamedSubjects\x12\x18.casbin.SimpleGetRequest\x1a\x12.casbin.ArrayReply\"\x00\x12;\n" +
	"\rGetAllObjects\x12\x14.casbin.EmptyRequest\x1a\x12.casbin.ArrayReply\"\x00\x12D\n" +
	"\x12GetAllNamedObjects\x12\x18.casbin.SimpleGetRequest\x1a\x12.casbin.ArrayReply\"\x00\x12;\n" +
	"\rGetAllActions\x12\x14.casbin.EmptyRequest\x1a\x12.casbin.ArrayReply\"\x00\x12D\n" +
	"\x12GetAllNamedActions\x12\x18.casbin.SimpleGetRequest\x1a\x12.casbin.ArrayReply\"\x00\x129\n" +
	"\vGetAllRoles\x12\x14.casbin.EmptyRequest\x1a\x12.casbin.ArrayReply\"\x00\x12B\n" +
	"\x10GetAllNamedRoles\x12\x18.casbin.SimpleGetRequest\x1a\x12.casbin.ArrayReply\"\x00\x127\n" +
	"\tHasPolicy\x12\x15.casbin.PolicyRequest\x1a\x11.casbin.BoolReply\"\x00\x12<\n" +
	"\x0eHasNamedPolicy\x12\x15.casbin.PolicyRequest\x1a\x11.casbin.BoolReply\"\x00\x12?\n" +
	"\x11HasGroupingPolicy\x12\x15.casbin.PolicyRequest\x1a\x11.casbin.BoolReply\"\x00\x12D\n" +
	"\x16HasNamedGroupingPolicy\x12\x15.casbin.PolicyRequest\x1a\x11.casbin.BoolReply\"\x00\x12@\n" +
	"\fUpdatePolicy\x12\x1b.casbin.UpdatePolicyRequest\x1a\x11.casbin.BoolReply\"\x00\x12D\n" +
	"\x0eUpdatePolicies\x12\x1d.casbin.UpdatePoliciesRequest\x1a\x11.casbin.BoolReply\"\x00B\n" +
	"Z\b./casbinb\x06proto3"

var (
	file_casbin_casbin_proto_rawDescOnce sync.Once
	file_casbin_casbin_proto_rawDescData []byte
)

func file_casbin_casbin_proto_rawDescGZIP() []byte {
	file_casbin_casbin_proto_rawDescOnce.Do(func() {
		file_casbin_casbin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_casbin_casbin_proto_rawDesc), len(file_casbin_casbin_proto_rawDesc)))
	})
	return file_casbin_casbin_proto_rawDescData
}

var file_casbin_casbin_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_casbin_casbin_proto_goTypes = []any{
	(*NewEnforcerRequest)(nil),    // 0: casbin.NewEnforcerRequest
	(*NewEnforcerReply)(nil),      // 1: casbin.NewEnforcerReply
	(*NewAdapterRequest)(nil),     // 2: casbin.NewAdapterRequest
	(*NewAdapterReply)(nil),       // 3: casbin.NewAdapterReply
	(*EnforceRequest)(nil),        // 4: casbin.EnforceRequest
	(*BoolReply)(nil),             // 5: casbin.BoolReply
	(*EmptyRequest)(nil),          // 6: casbin.EmptyRequest
	(*EmptyReply)(nil),            // 7: casbin.EmptyReply
	(*PolicyRequest)(nil),         // 8: casbin.PolicyRequest
	(*SimpleGetRequest)(nil),      // 9: casbin.SimpleGetRequest
	(*ArrayReply)(nil),            // 10: casbin.ArrayReply
	(*FilteredPolicyRequest)(nil), // 11: casbin.FilteredPolicyRequest
	(*UserRoleRequest)(nil),       // 12: casbin.UserRoleRequest
	(*PermissionRequest)(nil),     // 13: casbin.PermissionRequest
	(*Array2DReply)(nil),          // 14: casbin.Array2DReply
	(*Array)(nil),                 // 15: casbin.Array
	(*Array2D)(nil),               // 16: casbin.Array2D
	(*UpdatePolicyRequest)(nil),   // 17: casbin.UpdatePolicyRequest
	(*UpdatePoliciesRequest)(nil), // 18: casbin.UpdatePoliciesRequest
	(*Array2DReplyD)(nil),         // 19: casbin.Array2DReply.d
}
var file_casbin_casbin_proto_depIdxs = []int32{
	19, // 0: casbin.Array2DReply.d2:type_name -> casbin.Array2DReply.d
	15, // 1: casbin.Array2D.array:type_name -> casbin.Array
	15, // 2: casbin.UpdatePolicyRequest.old:type_name -> casbin.Array
	15, // 3: casbin.UpdatePolicyRequest.new:type_name -> casbin.Array
	16, // 4: casbin.UpdatePoliciesRequest.old:type_name -> casbin.Array2D
	16, // 5: casbin.UpdatePoliciesRequest.new:type_name -> casbin.Array2D
	0,  // 6: casbin.Casbin.NewEnforcer:input_type -> casbin.NewEnforcerRequest
	2,  // 7: casbin.Casbin.NewAdapter:input_type -> casbin.NewAdapterRequest
	4,  // 8: casbin.Casbin.Enforce:input_type -> casbin.EnforceRequest
	6,  // 9: casbin.Casbin.LoadPolicy:input_type -> casbin.EmptyRequest
	6,  // 10: casbin.Casbin.SavePolicy:input_type -> casbin.EmptyRequest
	8,  // 11: casbin.Casbin.AddPolicy:input_type -> casbin.PolicyRequest
	8,  // 12: casbin.Casbin.AddNamedPolicy:input_type -> casbin.PolicyRequest
	8,  // 13: casbin.Casbin.RemovePolicy:input_type -> casbin.PolicyRequest
	8,  // 14: casbin.Casbin.RemoveNamedPolicy:input_type -> casbin.PolicyRequest
	11, // 15: casbin.Casbin.RemoveFilteredPolicy:input_type -> casbin.FilteredPolicyRequest
	11, // 16: casbin.Casbin.RemoveFilteredNamedPolicy:input_type -> casbin.FilteredPolicyRequest
	6,  // 17: casbin.Casbin.GetPolicy:input_type -> casbin.EmptyRequest
	8,  // 18: casbin.Casbin.GetNamedPolicy:input_type -> casbin.PolicyRequest
	11, // 19: casbin.Casbin.GetFilteredPolicy:input_type -> casbin.FilteredPolicyRequest
	11, // 20: casbin.Casbin.GetFilteredNamedPolicy:input_type -> casbin.FilteredPolicyRequest
	8,  // 21: casbin.Casbin.AddGroupingPolicy:input_type -> casbin.PolicyRequest
	8,  // 22: casbin.Casbin.AddNamedGroupingPolicy:input_type -> casbin.PolicyRequest
	8,  // 23: casbin.Casbin.RemoveGroupingPolicy:input_type -> casbin.PolicyRequest
	8,  // 24: casbin.Casbin.RemoveNamedGroupingPolicy:input_type -> casbin.PolicyRequest
	11, // 25: casbin.Casbin.RemoveFilteredGroupingPolicy:input_type -> casbin.FilteredPolicyRequest
	11, // 26: casbin.Casbin.RemoveFilteredNamedGroupingPolicy:input_type -> casbin.FilteredPolicyRequest
	6,  // 27: casbin.Casbin.GetGroupingPolicy:input_type -> casbin.EmptyRequest
	8,  // 28: casbin.Casbin.GetNamedGroupingPolicy:input_type -> casbin.PolicyRequest
	11, // 29: casbin.Casbin.GetFilteredGroupingPolicy:input_type -> casbin.FilteredPolicyRequest
	11, // 30: casbin.Casbin.GetFilteredNamedGroupingPolicy:input_type -> casbin.FilteredPolicyRequest
	6,  // 31: casbin.Casbin.GetAllSubjects:input_type -> casbin.EmptyRequest
	9,  // 32: casbin.Casbin.GetAllNamedSubjects:input_type -> casbin.SimpleGetRequest
	6,  // 33: casbin.Casbin.GetAllObjects:input_type -> casbin.EmptyRequest
	9,  // 34: casbin.Casbin.GetAllNamedObjects:input_type -> casbin.SimpleGetRequest
	6,  // 35: casbin.Casbin.GetAllActions:input_type -> casbin.EmptyRequest
	9,  // 36: casbin.Casbin.GetAllNamedActions:input_type -> casbin.SimpleGetRequest
	6,  // 37: casbin.Casbin.GetAllRoles:input_type -> casbin.EmptyRequest
	9,  // 38: casbin.Casbin.GetAllNamedRoles:input_type -> casbin.SimpleGetRequest
	8,  // 39: casbin.Casbin.HasPolicy:input_type -> casbin.PolicyRequest
	8,  // 40: casbin.Casbin.HasNamedPolicy:input_type -> casbin.PolicyRequest
	8,  // 41: casbin.Casbin.HasGroupingPolicy:input_type -> casbin.PolicyRequest
	8,  // 42: casbin.Casbin.HasNamedGroupingPolicy:input_type -> casbin.PolicyRequest
	17, // 43: casbin.Casbin.UpdatePolicy:input_type -> casbin.UpdatePolicyRequest
	18, // 44: casbin.Casbin.UpdatePolicies:input_type -> casbin.UpdatePoliciesRequest
	1,  // 45: casbin.Casbin.NewEnforcer:output_type -> casbin.NewEnforcerReply
	3,  // 46: casbin.Casbin.NewAdapter:output_type -> casbin.NewAdapterReply
	5,  // 47: casbin.Casbin.Enforce:output_type -> casbin.BoolReply
	7,  // 48: casbin.Casbin.LoadPolicy:output_type -> casbin.EmptyReply
	7,  // 49: casbin.Casbin.SavePolicy:output_type -> casbin.EmptyReply
	5,  // 50: casbin.Casbin.AddPolicy:output_type -> casbin.BoolReply
	5,  // 51: casbin.Casbin.AddNamedPolicy:output_type -> casbin.BoolReply
	5,  // 52: casbin.Casbin.RemovePolicy:output_type -> casbin.BoolReply
	5,  // 53: casbin.Casbin.RemoveNamedPolicy:output_type -> casbin.BoolReply
	5,  // 54: casbin.Casbin.RemoveFilteredPolicy:output_type -> casbin.BoolReply
	5,  // 55: casbin.Casbin.RemoveFilteredNamedPolicy:output_type -> casbin.BoolReply
	14, // 56: casbin.Casbin.GetPolicy:output_type -> casbin.Array2DReply
	14, // 57: casbin.Casbin.GetNamedPolicy:output_type -> casbin.Array2DReply
	14, // 58: casbin.Casbin.GetFilteredPolicy:output_type -> casbin.Array2DReply
	14, // 59: casbin.Casbin.GetFilteredNamedPolicy:output_type -> casbin.Array2DReply
	5,  // 60: casbin.Casbin.AddGroupingPolicy:output_type -> casbin.BoolReply
	5,  // 61: casbin.Casbin.AddNamedGroupingPolicy:output_type -> casbin.BoolReply
	5,  // 62: casbin.Casbin.RemoveGroupingPolicy:output_type -> casbin.BoolReply
	5,  // 63: casbin.Casbin.RemoveNamedGroupingPolicy:output_type -> casbin.BoolReply
	5,  // 64: casbin.Casbin.RemoveFilteredGroupingPolicy:output_type -> casbin.BoolReply
	5,  // 65: casbin.Casbin.RemoveFilteredNamedGroupingPolicy:output_type -> casbin.BoolReply
	14, // 66: casbin.Casbin.GetGroupingPolicy:output_type -> casbin.Array2DReply
	14, // 67: casbin.Casbin.GetNamedGroupingPolicy:output_type -> casbin.Array2DReply
	14, // 68: casbin.Casbin.GetFilteredGroupingPolicy:output_type -> casbin.Array2DReply
	14, // 69: casbin.Casbin.GetFilteredNamedGroupingPolicy:output_type -> casbin.Array2DReply
	10, // 70: casbin.Casbin.GetAllSubjects:output_type -> casbin.ArrayReply
	10, // 71: casbin.Casbin.GetAllNamedSubjects:output_type -> casbin.ArrayReply
	10, // 72: casbin.Casbin.GetAllObjects:output_type -> casbin.ArrayReply
	10, // 73: casbin.Casbin.GetAllNamedObjects:output_type -> casbin.ArrayReply
	10, // 74: casbin.Casbin.GetAllActions:output_type -> casbin.ArrayReply
	10, // 75: casbin.Casbin.GetAllNamedActions:output_type -> casbin.ArrayReply
	10, // 76: casbin.Casbin.GetAllRoles:output_type -> casbin.ArrayReply
	10, // 77: casbin.Casbin.GetAllNamedRoles:output_type -> casbin.ArrayReply
	5,  // 78: casbin.Casbin.HasPolicy:output_type -> casbin.BoolReply
	5,  // 79: casbin.Casbin.HasNamedPolicy:output_type -> casbin.BoolReply
	5,  // 80: casbin.Casbin.HasGroupingPolicy:output_type -> casbin.BoolReply
	5,  // 81: casbin.Casbin.HasNamedGroupingPolicy:output_type -> casbin.BoolReply
	5,  // 82: casbin.Casbin.UpdatePolicy:output_type -> casbin.BoolReply
	5,  // 83: casbin.Casbin.UpdatePolicies:output_type -> casbin.BoolReply
	45, // [45:84] is the sub-list for method output_type
	6,  // [6:45] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_casbin_casbin_proto_init() }
func file_casbin_casbin_proto_init() {
	if File_casbin_casbin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_casbin_casbin_proto_rawDesc), len(file_casbin_casbin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_casbin_casbin_proto_goTypes,
		DependencyIndexes: file_casbin_casbin_proto_depIdxs,
		MessageInfos:      file_casbin_casbin_proto_msgTypes,
	}.Build()
	File_casbin_casbin_proto = out.File
	file_casbin_casbin_proto_goTypes = nil
	file_casbin_casbin_proto_depIdxs = nil
}
