// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: portal.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 下发命令的请求体
type CmdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`      // 命令唯一标识，后台生成
	Uuids         []string               `protobuf:"bytes,2,rep,name=uuids,proto3" json:"uuids,omitempty"` // 下发的agent uuid 列表
	Cmd           *Command               `protobuf:"bytes,3,opt,name=cmd,proto3" json:"cmd,omitempty"`     // 命令内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdRequest) Reset() {
	*x = CmdRequest{}
	mi := &file_portal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdRequest) ProtoMessage() {}

func (x *CmdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdRequest.ProtoReflect.Descriptor instead.
func (*CmdRequest) Descriptor() ([]byte, []int) {
	return file_portal_proto_rawDescGZIP(), []int{0}
}

func (x *CmdRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CmdRequest) GetUuids() []string {
	if x != nil {
		return x.Uuids
	}
	return nil
}

func (x *CmdRequest) GetCmd() *Command {
	if x != nil {
		return x.Cmd
	}
	return nil
}

// 日志上报
type LogReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`    // 任务唯一标识
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"` // 日志 uuid 标识
	Pc            int32                  `protobuf:"zigzag32,3,opt,name=pc,proto3" json:"pc,omitempty"`  // 进度百分比 [0-100], 特殊 -100 表失败结束
	Line          *Line                  `protobuf:"bytes,4,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogReply) Reset() {
	*x = LogReply{}
	mi := &file_portal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogReply) ProtoMessage() {}

func (x *LogReply) ProtoReflect() protoreflect.Message {
	mi := &file_portal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogReply.ProtoReflect.Descriptor instead.
func (*LogReply) Descriptor() ([]byte, []int) {
	return file_portal_proto_rawDescGZIP(), []int{1}
}

func (x *LogReply) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LogReply) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *LogReply) GetPc() int32 {
	if x != nil {
		return x.Pc
	}
	return 0
}

func (x *LogReply) GetLine() *Line {
	if x != nil {
		return x.Line
	}
	return nil
}

// 一般信息定义，由客户端根据类型自行解析消息体
type MsgReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                          // 任务唯一标识
	Mt            string                 `protobuf:"bytes,2,opt,name=mt,proto3" json:"mt,omitempty"`                           // 消息类型
	Uuid          string                 `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`                       // 消息 uuid 标识
	Stat          Status                 `protobuf:"varint,4,opt,name=stat,proto3,enum=protobuf.Status" json:"stat,omitempty"` // 状态，成功或者失败
	Body          *Body                  `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`                       // 消息体, 状态为失败时则消息体无法被信任
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgReply) Reset() {
	*x = MsgReply{}
	mi := &file_portal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgReply) ProtoMessage() {}

func (x *MsgReply) ProtoReflect() protoreflect.Message {
	mi := &file_portal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgReply.ProtoReflect.Descriptor instead.
func (*MsgReply) Descriptor() ([]byte, []int) {
	return file_portal_proto_rawDescGZIP(), []int{2}
}

func (x *MsgReply) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MsgReply) GetMt() string {
	if x != nil {
		return x.Mt
	}
	return ""
}

func (x *MsgReply) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *MsgReply) GetStat() Status {
	if x != nil {
		return x.Stat
	}
	return Status_SUCC
}

func (x *MsgReply) GetBody() *Body {
	if x != nil {
		return x.Body
	}
	return nil
}

// agent 节点信息
type NodeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Ts            int64                  `protobuf:"varint,4,opt,name=ts,proto3" json:"ts,omitempty"` // 最后上报时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeReply) Reset() {
	*x = NodeReply{}
	mi := &file_portal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeReply) ProtoMessage() {}

func (x *NodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_portal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeReply.ProtoReflect.Descriptor instead.
func (*NodeReply) Descriptor() ([]byte, []int) {
	return file_portal_proto_rawDescGZIP(), []int{3}
}

func (x *NodeReply) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *NodeReply) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NodeReply) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *NodeReply) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

// 订阅的消息载荷
type Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`    // 任务唯一标识
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"` // 消息 uuid 标识
	Ts            int64                  `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`    // 请求时间戳
	Dt            uint32                 `protobuf:"varint,4,opt,name=dt,proto3" json:"dt,omitempty"`    // 数据类型
	Body          []byte                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"` // 数据内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_portal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_portal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_portal_proto_rawDescGZIP(), []int{4}
}

func (x *Payload) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Payload) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Payload) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *Payload) GetDt() uint32 {
	if x != nil {
		return x.Dt
	}
	return 0
}

func (x *Payload) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// 文件分片上传, gRPC guarantees shard ordering
type FileShard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`      // 唯一标识
	Fn            string                 `protobuf:"bytes,2,opt,name=fn,proto3" json:"fn,omitempty"`       // filename
	Piece         []byte                 `protobuf:"bytes,3,opt,name=piece,proto3" json:"piece,omitempty"` // file content piece
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileShard) Reset() {
	*x = FileShard{}
	mi := &file_portal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileShard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileShard) ProtoMessage() {}

func (x *FileShard) ProtoReflect() protoreflect.Message {
	mi := &file_portal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileShard.ProtoReflect.Descriptor instead.
func (*FileShard) Descriptor() ([]byte, []int) {
	return file_portal_proto_rawDescGZIP(), []int{5}
}

func (x *FileShard) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FileShard) GetFn() string {
	if x != nil {
		return x.Fn
	}
	return ""
}

func (x *FileShard) GetPiece() []byte {
	if x != nil {
		return x.Piece
	}
	return nil
}

// 文件md5值统计信息
type FileMd5Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Md5S          map[string]string      `protobuf:"bytes,1,rep,name=md5s,proto3" json:"md5s,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 文件名->md5值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMd5Reply) Reset() {
	*x = FileMd5Reply{}
	mi := &file_portal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMd5Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMd5Reply) ProtoMessage() {}

func (x *FileMd5Reply) ProtoReflect() protoreflect.Message {
	mi := &file_portal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMd5Reply.ProtoReflect.Descriptor instead.
func (*FileMd5Reply) Descriptor() ([]byte, []int) {
	return file_portal_proto_rawDescGZIP(), []int{6}
}

func (x *FileMd5Reply) GetMd5S() map[string]string {
	if x != nil {
		return x.Md5S
	}
	return nil
}

// agent 节点变化
type NodeEventReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// update delete
	Type          string     `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Node          *NodeReply `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeEventReply) Reset() {
	*x = NodeEventReply{}
	mi := &file_portal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeEventReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeEventReply) ProtoMessage() {}

func (x *NodeEventReply) ProtoReflect() protoreflect.Message {
	mi := &file_portal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeEventReply.ProtoReflect.Descriptor instead.
func (*NodeEventReply) Descriptor() ([]byte, []int) {
	return file_portal_proto_rawDescGZIP(), []int{7}
}

func (x *NodeEventReply) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NodeEventReply) GetNode() *NodeReply {
	if x != nil {
		return x.Node
	}
	return nil
}

var File_portal_proto protoreflect.FileDescriptor

const file_portal_proto_rawDesc = "" +
	"\n" +
	"\fportal.proto\x12\bprotobuf\x1a\fcommon.proto\"W\n" +
	"\n" +
	"CmdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05uuids\x18\x02 \x03(\tR\x05uuids\x12#\n" +
	"\x03cmd\x18\x03 \x01(\v2\x11.protobuf.CommandR\x03cmd\"b\n" +
	"\bLogReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x0e\n" +
	"\x02pc\x18\x03 \x01(\x11R\x02pc\x12\"\n" +
	"\x04line\x18\x04 \x01(\v2\x0e.protobuf.LineR\x04line\"\x88\x01\n" +
	"\bMsgReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x0e\n" +
	"\x02mt\x18\x02 \x01(\tR\x02mt\x12\x12\n" +
	"\x04uuid\x18\x03 \x01(\tR\x04uuid\x12$\n" +
	"\x04stat\x18\x04 \x01(\x0e2\x10.protobuf.StatusR\x04stat\x12\"\n" +
	"\x04body\x18\x05 \x01(\v2\x0e.protobuf.BodyR\x04body\"[\n" +
	"\tNodeReply\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x0e\n" +
	"\x02ts\x18\x04 \x01(\x03R\x02ts\"a\n" +
	"\aPayload\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x0e\n" +
	"\x02ts\x18\x03 \x01(\x03R\x02ts\x12\x0e\n" +
	"\x02dt\x18\x04 \x01(\rR\x02dt\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\"A\n" +
	"\tFileShard\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x0e\n" +
	"\x02fn\x18\x02 \x01(\tR\x02fn\x12\x14\n" +
	"\x05piece\x18\x03 \x01(\fR\x05piece\"}\n" +
	"\fFileMd5Reply\x124\n" +
	"\x04md5s\x18\x01 \x03(\v2 .protobuf.FileMd5Reply.Md5sEntryR\x04md5s\x1a7\n" +
	"\tMd5sEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\x0eNodeEventReply\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12'\n" +
	"\x04node\x18\x02 \x01(\v2\x13.protobuf.NodeReplyR\x04node2\xd1\x02\n" +
	"\rCruiserPortal\x121\n" +
	"\x05Nodes\x12\x0f.protobuf.Empty\x1a\x13.protobuf.NodeReply\"\x000\x01\x122\n" +
	"\aExecCmd\x12\x14.protobuf.CmdRequest\x1a\x0f.protobuf.Empty\"\x00\x123\n" +
	"\tSubscribe\x12\x0f.protobuf.Empty\x1a\x11.protobuf.Payload\"\x000\x01\x121\n" +
	"\aPutFile\x12\x13.protobuf.FileShard\x1a\x0f.protobuf.Empty(\x01\x124\n" +
	"\aFileMd5\x12\x0f.protobuf.Empty\x1a\x16.protobuf.FileMd5Reply\"\x00\x12;\n" +
	"\n" +
	"WatchNodes\x12\x0f.protobuf.Empty\x1a\x18.protobuf.NodeEventReply\"\x000\x01B\x03Z\x01.b\x06proto3"

var (
	file_portal_proto_rawDescOnce sync.Once
	file_portal_proto_rawDescData []byte
)

func file_portal_proto_rawDescGZIP() []byte {
	file_portal_proto_rawDescOnce.Do(func() {
		file_portal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_portal_proto_rawDesc), len(file_portal_proto_rawDesc)))
	})
	return file_portal_proto_rawDescData
}

var file_portal_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_portal_proto_goTypes = []any{
	(*CmdRequest)(nil),     // 0: protobuf.CmdRequest
	(*LogReply)(nil),       // 1: protobuf.LogReply
	(*MsgReply)(nil),       // 2: protobuf.MsgReply
	(*NodeReply)(nil),      // 3: protobuf.NodeReply
	(*Payload)(nil),        // 4: protobuf.Payload
	(*FileShard)(nil),      // 5: protobuf.FileShard
	(*FileMd5Reply)(nil),   // 6: protobuf.FileMd5Reply
	(*NodeEventReply)(nil), // 7: protobuf.NodeEventReply
	nil,                    // 8: protobuf.FileMd5Reply.Md5sEntry
	(*Command)(nil),        // 9: protobuf.Command
	(*Line)(nil),           // 10: protobuf.Line
	(Status)(0),            // 11: protobuf.Status
	(*Body)(nil),           // 12: protobuf.Body
	(*Empty)(nil),          // 13: protobuf.Empty
}
var file_portal_proto_depIdxs = []int32{
	9,  // 0: protobuf.CmdRequest.cmd:type_name -> protobuf.Command
	10, // 1: protobuf.LogReply.line:type_name -> protobuf.Line
	11, // 2: protobuf.MsgReply.stat:type_name -> protobuf.Status
	12, // 3: protobuf.MsgReply.body:type_name -> protobuf.Body
	8,  // 4: protobuf.FileMd5Reply.md5s:type_name -> protobuf.FileMd5Reply.Md5sEntry
	3,  // 5: protobuf.NodeEventReply.node:type_name -> protobuf.NodeReply
	13, // 6: protobuf.CruiserPortal.Nodes:input_type -> protobuf.Empty
	0,  // 7: protobuf.CruiserPortal.ExecCmd:input_type -> protobuf.CmdRequest
	13, // 8: protobuf.CruiserPortal.Subscribe:input_type -> protobuf.Empty
	5,  // 9: protobuf.CruiserPortal.PutFile:input_type -> protobuf.FileShard
	13, // 10: protobuf.CruiserPortal.FileMd5:input_type -> protobuf.Empty
	13, // 11: protobuf.CruiserPortal.WatchNodes:input_type -> protobuf.Empty
	3,  // 12: protobuf.CruiserPortal.Nodes:output_type -> protobuf.NodeReply
	13, // 13: protobuf.CruiserPortal.ExecCmd:output_type -> protobuf.Empty
	4,  // 14: protobuf.CruiserPortal.Subscribe:output_type -> protobuf.Payload
	13, // 15: protobuf.CruiserPortal.PutFile:output_type -> protobuf.Empty
	6,  // 16: protobuf.CruiserPortal.FileMd5:output_type -> protobuf.FileMd5Reply
	7,  // 17: protobuf.CruiserPortal.WatchNodes:output_type -> protobuf.NodeEventReply
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_portal_proto_init() }
func file_portal_proto_init() {
	if File_portal_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_portal_proto_rawDesc), len(file_portal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_portal_proto_goTypes,
		DependencyIndexes: file_portal_proto_depIdxs,
		MessageInfos:      file_portal_proto_msgTypes,
	}.Build()
	File_portal_proto = out.File
	file_portal_proto_goTypes = nil
	file_portal_proto_depIdxs = nil
}
